name: kboxjson
on: 
  push:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:
    
jobs:

  my-job:

    name: My Job

    runs-on: ubuntu-latest

    environment:
      name: github-pages    
    
    steps:

    - uses: actions/checkout@v2

    - name: Print a greeting

      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
        URLMK: ${{ secrets.URLMK }}
        
      run: |
        UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46';
        [ -d fmlist ] || mkdir fmlist
        [ -d fmsongs ] || mkdir fmsongs
        [ -d songinfo ] || mkdir songinfo
        pagesize=1
        pageindex=1
        urllist="$URLMK/fmList.php?pagesize=$pagesize&pageindex=$pageindex";
        jsonlist=$(curl -s "$urllist")
        [[ $jsonlist == \"* ]] && jsonlist=$(eval echo "$jsonlist")
        echo "$urllist"
        #echo "$jsonlist"
        main="def main():
          import sys, json
          print(json.load(sys.stdin)['recordcount'])"
        py=$(echo -e "$main\nmain()")
        echo "$py"
        pagesize=$(echo "$jsonlist" | python3 -c "$py")

        echo $pagesize
        urllist="$URLMK/fmList.php?pagesize=$pagesize&pageindex=$pageindex";
        jsonlist=$(curl -s "$urllist")
        [[ $jsonlist == \"* ]] && jsonlist=$(eval echo "$jsonlist")
        #-o "fmlist/$pageindex.json" 
        main="def main():
          import sys, json
          fmlist=json.load(sys.stdin)
          for fm in fmlist['data']:
            print(fm['fmid'])"
        py=$(echo -e "$main\nmain()")
        #echo "$jsonlist"
        echo "$py"
        loop="YES"
        for fmid in $(echo "$jsonlist" | python3 -c "$py")
        do
          [ -z $loop ] && break
          echo "$fmid"
          for pageindex in {1..3}
          do
            [ -z $loop ] && break
            if [ -z $"offset" ]; then
              urlsongs="$URLMK/fmSongs.php?size=20&fmid=$fmid"
            else
              urlsongs="$URLMK/fmSongs.php?size=20&fmid=$fmid&offset=$offset"
            fi
            jsonsongs=$(curl -s "$urlsongs")
            [[ $jsonsongs == \"* ]] && jsonsongs=$(eval echo "$jsonsongs")
            main="def main():
              import sys, json
              fmsongs=json.load(sys.stdin)
              if fmsongs['data'][0]['songs'] is None:
                print("0")
              else:
                print(len(fmsongs['data'][0]['songs']))"
            py=$(echo -e "$main\nmain()")
            lensongs=$(echo "$jsonsongs" | python3 -c "$py")
            echo "$lensongs"
            if [ "$lensongs" -eq "0" ]; then
              [ -d "fmsongs/$fmid" ] && rm -rf "fmsongs/$fmid"
            else
              [ -d "fmsongs/$fmid" ] || mkdir "fmsongs/$fmid"
              filesongs="fmsongs/$fmid/$pageindex.json"
              echo $jsonsongs > "$filesongs"

              main="def main():
                import sys, json
                fmsongs=json.load(sys.stdin)
                for song in fmsongs['data'][0]['songs']:
                  print(song['hash'])"
              py=$(echo -e "$main\nmain()")
              urlhash="$URLMK/getSongInfo.php?cmd=playInfo&hash="
              for hash in $(echo "$jsonsongs" | python3 -c "$py")
              do
                [ -z $loop ] && break
                filehash="songinfo/$hash.json"
                if [ -f "$filehash" ]; then
                  if grep -q '"error":""' "$filehash"; then
                    continue
                  else
                    rm -f "$filehash"
                  fi
                fi
                jsonhash=$(curl -v "$urlhash$hash" -A "$UA")
                [[ $jsonhash == \"* ]] && jsonhash=$(eval echo "$jsonhash")
                if echo "$jsonhash" | grep -q '"error":""'; then
                  echo $jsonhash > "$filehash"
                else
                  echo "$jsonhash"
                fi
                if echo "$jsonhash" | grep -q '"error":"您操作太频繁了，请稍后再试"'; then
                  loop=""
                  echo "QUIT"
                fi
                sleep 10
              done
            fi
            
            main="def main():
              import sys, json
              fmsongs=json.load(sys.stdin)
              print(fmsongs['data'][0]['offset'])"
            py=$(echo -e "$main\nmain()")
            offset=$(echo "$jsonsongs" | python3 -c "$py")
            #offset=$(grep -o 'offset[^,]*\",' "$fsongs" |grep -o '%7B.*%7D')
            echo "$offset"
          done
        done
        
        curl -k -o bing.json "https://bing.com/HPImageArchive.aspx?format=js&idx=0&n=8"
        curl -k -o pixabay.json "${{ secrets.PIXABAY }}"
        if [ $? -eq 0 ]; then
          sed -i 's|\"largeImageURL"|\"_largeImageURL"|g' pixabay.json
          sed -i 's|\"previewURL"|\"largeImageURL"|g' pixabay.json
          sed -i 's|\_150.jpg|\_960_720.jpg|g' pixabay.json
        fi
        curl -k -o vladstudio.json "https://vlad.studio/api/v3/art/?client=${{ secrets.VLADSTUDIO }}&format=json&has_wall=1&limit=600"
        if [ $? -eq 0 ]; then
          sed -i 's|api\\\/v3\\\/download?client=.\{24\}&filename|ajax-download-wallpaper-image\\\/?filename|g' vladstudio.json
          sed -i 's|\&size=1600x1200|\&size=1920x1080|g' vladstudio.json
        fi
        curl -k -o unsplash.json "${{ secrets.UNSPLASH }}1"
        if [ $? -eq 0 ]; then
          for p in 2 3 4 5 6 ; do
            curl -k -o unsplash_tmp.json "${{ secrets.UNSPLASH }}$p"
            if [ $? -eq 0 ]; then
              json=$(cat unsplash.json)
              json=${json%*\]}
              tmp=$(cat unsplash_tmp.json)
              tmp=${tmp#*\[}
              echo "$json,$tmp" > unsplash.json
            fi
          done
        fi

    - name: Cleanup
      run: |
          rm -f upload.txt
          rm -f unsplash_tmp.json
          
    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: "Action Auto"
