name: kboxjson

on: [push]

jobs:
  runMultipleCommands:
    runs-on: ubuntu-latest
    steps:
     - run: |
        echo "A initial message $TOKEN"
        echo "Another message or command"
     - run: echo "One last message"
     - env:
        TOKEN: ${{ secrets.TOKEN }}
